// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCO4O24t2hcegwzqUDjNqD39Dv8KXs4ng',
    appId: '1:162542608755:web:1720f99c39aa09ff7ca506',
    messagingSenderId: '162542608755',
    projectId: 'safe-wave-f1a3c',
    authDomain: 'safe-wave-f1a3c.firebaseapp.com',
    storageBucket: 'safe-wave-f1a3c.appspot.com',
    measurementId: 'G-PBJ8W3WN77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlLlCCjiPuCX7fi5vrvKbdnVHrrlpsV50',
    appId: '1:162542608755:android:f8bb281de15f35cc7ca506',
    messagingSenderId: '162542608755',
    projectId: 'safe-wave-f1a3c',
    storageBucket: 'safe-wave-f1a3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7JHrBn4Vb_tTv3uGeXn4wn4Wc__df_dc',
    appId: '1:162542608755:ios:629049e0658f69267ca506',
    messagingSenderId: '162542608755',
    projectId: 'safe-wave-f1a3c',
    storageBucket: 'safe-wave-f1a3c.appspot.com',
    iosBundleId: 'com.example.safeWave',
  );
}
